#ifndef SYMMETRY_LIMITS_H
#define SYMMETRY_LIMITS_H

#define MAX_ENTITY_NAME_LEN 128

#define MAX_FILENAME_LEN 128

#define MAX_EVENTS 128
#define MAX_EVENT_SUBSCRIPTIONS 2048

#define MAX_SCENE_ENTITIES          32
#define MAX_SCENE_LIGHTS            30
#define MAX_SCENE_CAMERAS           2
#define MAX_SCENE_STATIC_MESHES     1024
#define MAX_SCENE_SOUND_SOURCES     128
#define MAX_SCENE_ENTITY_ARCHETYPES 32
#define MAX_SCENE_ENEMIES           64
#define MAX_SCENE_TRIGGERS          256
#define MAX_SCENE_DOORS             256
#define MAX_SCENE_PICKUPS           32

#define MAX_UNIFORM_NAME_LEN 64

#define MAX_MATERIAL_REGISTERED_STATIC_MESHES 1024

#define MAX_FRAME_TIME 0.5f

#define MAX_ENEMY_SOUND_SOURCES 2
#define MAX_ENEMY_MESHES 2
#define MAX_ENEMY_LIGHTS 1

#define MAX_CONSOLE_MESSAGE_LEN 256
#define MAX_CONSOLE_MESSAGES    1024
#define MAX_CONSOLE_COMMAND_LEN 32
#define MAX_CONSOLE_HISTORY     64

#define MAX_DEBUG_VAR_NAME                64
#define MAX_DEBUG_VARS_PER_FRAME_NUMERIC  64
#define MAX_DEBUG_VARS_PER_FRAME_TEXTURES 8

#define HASH_MAP_NUM_BUCKETS 10
#define MAX_HASH_KEY_LEN     64

#define MAX_PLAYER_HEALTH 100

#define MAX_EDITOR_NOTIFICATION_MESSAGE_LEN 256

#endif
