#ifndef SYMMETRY_LIMITS_H
#define SYMMETRY_LIMITS_H

#define MAX_ENTITY_NAME_LEN 128

#define MAX_FILENAME_LEN 128

#define MAX_EVENTS 128
#define MAX_EVENT_SUBSCRIPTIONS 2048

#define MAX_SCENE_ENTITIES          32
#define MAX_SCENE_LIGHTS            30
#define MAX_SCENE_CAMERAS           2
#define MAX_SCENE_STATIC_MESHES     1024
#define MAX_SCENE_SOUND_SOURCES     128
#define MAX_SCENE_ENTITY_ARCHETYPES 32
#define MAX_SCENE_ENEMIES           64

#define MAX_UNIFORM_NAME_LEN 64

#define MAX_MATERIAL_REGISTERED_STATIC_MESHES 1024

#endif
