#ifndef SYMMETRY_VERSION_FILE
#define SYMMETRY_VERSION_FILE

/* Auto generated version file. DO NOT MODIFY */
#define SYMMETRY_VERSION_MAJOR 0
#define SYMMETRY_VERSION_MINOR 4
#define SYMMETRY_VERSION_REVISION 377
#define SYMMETRY_VERSION_BRANCH "dev"

#endif