#ifndef SYMMETRY_VERSION_FILE
#define SYMMETRY_VERSION_FILE

/* Auto generated version file. DO NOT MODIFY */
#define SYMMETRY_VERSION_MAJOR 1
#define SYMMETRY_VERSION_MINOR 0
#define SYMMETRY_VERSION_REVISION 378
#define SYMMETRY_VERSION_BRANCH "dev"

#endif