#ifndef SYMMETRY_VERSION_FILE
#define SYMMETRY_VERSION_FILE

/* Auto generated version file. DO NOT MODIFY */
#define SYMMETRY_VERSION_MAJOR 0
#define SYMMETRY_VERSION_MINOR 3
#define SYMMETRY_VERSION_REVISION 374
#define SYMMETRY_VERSION_BRANCH "dev"

#endif